### ISSUE TITLE
Log file

### ISSUE THREAD

**Issue by rbrtbnfgl** [netgroup-polito/frog4-virtualizer#2]
I suggest to not use print on the project but to use the logging python class that helps to generate a log file.

**Comment by frisso** [comment]
Please take inspiration from other projects (e.g., frog4) that use the same architecture, including how to configure the log file in config.ini.

**Comment by francesco9911** [comment]
I used the logging python class that now print the log in a log file that can be setted (name file and log level) in the configuration file.

commit cff24e31abf9a045b2327e23c07ee635e6a7be39 in the branch new-api

**Comment by francesco9911** [comment]
I added parsing errors report in the log instead of print
commit c5ea0199037310fa74ab18efea2cbaa92e66635e on branch new-api

**Comment by frisso** [comment]
Thanks.
