### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/frog4-virtualizer#5]
1) Write a short text in the main readme about examples, and move the documentation of the examples in the proper folders.
2) Why there are more examples (.e., XML) than the documented ones?

**Comment by francesco9911** [comment]
I have created a new directory named nffg_examples (that stores 2 nffg in escape format, one create an instance of a vm and the second delete it) and reported in the README file.

commit 53217c91637f5bd37f07b2eb170fd09a509f9dbe on branch new-api

**Comment by frisso** [comment]
Thanks.
