### ISSUE TITLE
Remove "universal node" from the repository

### ISSUE THREAD

**Issue by frisso** [netgroup-polito/frog4-virtualizer#8]
The "universal node" term is used in several places, also in the code (e.g., virtualizer.py).
Remove it, as we're controlling a generic FROG4 domain, not just the universal node.

**Comment by francesco9911** [comment]
Removed the term universal-node with more generic domain word.
commit f684bcb571a4d5d4914b7052be94af6d1cbf67af on branch new-api

**Comment by frisso** [comment]
Thanks,
